Dashboard output
BoavidaGuerra/pitcher pull request #9
Opened 2020-11-18 16:31 UTC by Mauri-03

2020-11-18 21:24 UTC, volivers requested changes
@Mauri-03 Please review the commented script 🤪

2020-11-18 21:24 UTC, volivers commented on app/views/demos/show.html.erb
> +          <p><%= @pitch.pain %></p>
Shouldn't it be inside the loop?

2020-11-18 21:24 UTC, volivers commented on app/views/demos/show.html.erb
> +              <p><%= @persona.name %></p>
Please remove the @'s inside this loop

2020-11-19 11:33 UTC, BoavidaGuerra approved these changes

2020-11-19 11:35 UTC, merged